apiVersion: cache.example.com/v1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached-sample
    app.kubernetes.io/part-of: cnf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cnf-operator
  name: memcached-sample
spec:
  # TODO(user): Add fields here
  size: 3
